name: Silvertop.SemanticVersioning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_CONFIGURATION: Release
  SOLUTION_NAME: Silvertop.SemanticVersioning.sln

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.calculate-gitversion.outputs.semVer }}
    steps:

      - name: Checkout Source
        id:   checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set Up .NET
        id:   setup-dot-net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x

      - name: Install GitVersion
        id:   install-git-version
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'
        
      - name: Calculate Semantic Version
        id:   calculate-gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true

      - name: Restore Packages
        id:   restore-packages
        run:  dotnet restore
        
      - name: Build
        id:   build
        run:  dotnet build ${{env.SOLUTION_NAME}} --no-restore --configuration ${{env.BUILD_CONFIGURATION}} /p:Version=${{ steps.calculate-gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.calculate-gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.calculate-gitversion.outputs.semVer }}
    
      - name: Test
        id:   test
        run:  dotnet test --no-build --configuration ${{env.BUILD_CONFIGURATION}} --collect:"XPlat Code Coverage" --logger "GitHubActions"

      - name: Upload coverage
        id:   upload-coverage
        uses: actions/upload-artifact@v3
        with:
          name: Code Coverage
          path: "**/coverage.cobertura.xml"

      - name: Generate Coverage Report
        id:   generate-coverage-report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.9
        with:
          reports: "**/coverage.cobertura.xml"
          targetdir: "coverage-report"
          reporttypes: "Cobertura"

      - name: Publish Coverage to Codacy
        id:   publish-coverage-report
        uses: codacy/codacy-coverage-reporter-action@master
        if:   github.event_name == 'push'
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage-report/Cobertura.xml

      - name: Create Packages
        id:   create-packages
        run:  dotnet pack --configuration ${{env.BUILD_CONFIGURATION}} --output ./packages

      - name: Upload Packages
        id:   upload-packages
        uses: actions/upload-artifact@v3
        with:
          name: NuGetPackages
          path: packages/*.*

      - name: Tag Build
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.calculate-gitversion.outputs.fullSemVer }}',
              sha: context.sha
            })

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: Public NuGet Feed
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        id:   checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set Up .NET
        id:   setup-dot-net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
            5.0.x
            6.0.x  

      - name: Download Artifacts
        id:   download-artifacts
        uses: actions/download-artifact@v3
        with:
          name: NuGetPackages
          path: packages

      - name: Push packages 
        id:   push-packages
        run:  dotnet nuget push "packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ needs.build.outputs.semVer }}
          tag_name: v${{ needs.build.outputs.semVer }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true

      - name: Comment Release
        uses: apexskier/github-release-commenter@v1.3.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            This is addressed in release {release_link}.
          label-template: |
            state: released